version: 2

project_name: try

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: try
    main: ./cmd/try
    binary: try
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/upamune/try-go/internal/try.version={{ .Version }}
      - -X github.com/upamune/try-go/internal/try.commit={{ .FullCommit }}
      - -X github.com/upamune/try-go/internal/try.shortCommit={{ .ShortCommit }}

archives:
  - id: default
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "try_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto

brews:
  - name: try
    repository:
      owner: upamune
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:
      name: github-actions[bot]
      email: github-actions[bot]@users.noreply.github.com
    homepage: "https://github.com/upamune/try-go"
    description: "Ephemeral workspace manager"
    test: |
      system "#{bin}/try", "--version"
